#ifndef MUSICQQQUERYINTERFACE_H
#define MUSICQQQUERYINTERFACE_H

/* =================================================
 * This file is part of the TTK Music Player project
 * Copyright (C) 2015 - 2021 Greedysky Studio

 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License along
 * with this program; If not, see <http://www.gnu.org/licenses/>.
 ================================================= */

#include "musicobject.h"
#include "musicglobaldefine.h"

///cookie url
const QString QQ_UA_URL                 = "NW9YVlRXYnBnNlBFS3Ardi9VR295R0l2aW43U3JvRlpWc1AxMkI2K1MvN3RMVjdsOGhZMVlPRmIrais2ajBJUW1UbmxBRjlyS25WNHRyU0FYbFFMeWFpMUo5YWxFNnkweHd6RERnPT0=";
///song url
const QString QQ_SONG_SEARCH_URL        = "MjJ5MjdCbU1OUjdQWi90Ni9aUmJrVEJLN2lnazl3VEtMaWJwREoxWDJ3YVpKZWVHLzQ3Y0pXdWRDcDNpemw0a3dDditTQ0hrT3padGlOOG1VUXhkdFAzSkxYK1EzUlVzVGpzM25maHgxR0pmOGpKM3Z5dFROTEZGRitaaDJnbGtEWU0zOEJCWTB6cTBRT1FSMTVLMzhOWmJEdnV3ZHhOdW53VC9FcmFMMjRBWEFBNk1BY21vZmRQaEVtWHNYYmVVNWtjMFJRQk5XQUkwcjczUzlxa3AxZmY5d1V5Kzg2Szd5UzZFWnRBYTkrV1o1N1NWMU1iQVJ5dlBmUzFvWGgwT0hkOElNbmN3ZUxBdU5CRFlPdW92MEVhUEZ0eitYbDdzQTJCbG1xZ2xkNUtidHQzWmxVVlowMlVQMSt6VVR0dThLSmVBTnkrVEtqdnhJU2NCR3VuN3k4WW52b2E0c1ZHMUkvT3NtQ2pqcnh2OHF3T3J2Y21UZUlMbmlqWnozTnlINWs2QXo2QjhETWs9";
const QString QQ_SONG_INFO_URL          = "VTl3Ykp1cUk5TEFvY1JIc1E2aUFneXV4Y1VGRlVxVFM5ZTI2a283bExrNzk3WFl6ZEdneVdVN0JDeC9jUFRwVG9lTDBCVVphNWNlQTVXcnovV0lSZnZFOEZQcDFMdnNOdW1naitVdFJ4MFU9";
const QString QQ_SONG_LRC_URL           = "UkRvUTU1MHJGMmVDNDhRUWpXbnluVzViaVo0dGVKUHlxWHpnYzEvMnR2VU81WlJxYWpqY0ZEMC84anhRN3kwbm0vUGNxR20zZ1laUzg4Um5EOEdIL0FGS3pvK3VUMEgwMW1BaHFSYlA1OHJUSC9tQmpjUWVxTXk3RFo4PQ==";
const QString QQ_SONG_PIC_URL           = "ZUZWTnkreFptcVRkQ3Z3YW9hdVRHUi90Q2hLWjlrLzB6NlFDSUNnZWZKNnZhUXNXWCtpS3hoZGVpZGlFbmdwRDhWNmFxb3JMTUIyYlY2NDQ=";
const QString QQ_SONG_PREFIX_URL        = "NHZyWXlyaVZYbnlucTNGcDFsTGY3dDlsSm5wSGR0OGcvRUdjaElMdFhqUVU1YzNFK3N2N3dqYXI4c3ZJdDJzKzVvUUZjdz09";
const QString QQ_SONG_KEY_URL           = "elMxK3laMEhVOFdNYlE1eWdPck5vWnI5YTZpVS9lUGdtSlhPU3grRUJlRUYvVG5va2tvbUJrakZ6R3UvOU5uSFZuLzBvVzNwS24xSWZVbzQydWhqRFRncm1vTERtdkV6L1M5Z2RJejFBS0VKdTJWQ1ZST0dhZi9tUmxudmp3NC9EaGMxcXNyYmU3VWJIRzVkQlV5NFkrWXI3WkNDamozYmNqTDR4eG9mSkIwNWJTcEdlaGJwNkxvTmJyc3o4dllrVDROalUySHYyL21iQVBZVGRMU0FINllTV2xjc2RBNlFhcWlibUFMWUxLalBBOEpRdUJLamZIYXVRYTNVbTdWeU1UNVZlUHkrdnpXSzFVSVRxcjU5NEpOeXhTVHZuRGpKRTc1R2dYeEZPY1p5M2hFdnJ0UnFXZmZFa0NMUE1VSDFWSjkzM05BRkdtU0ZrN0JBM3M2L1NQcWRzamUxSGpqQWZ2dDdlUHdGUnB3cHpRSm9uU0Jqc3RoK0dWWHMyQjF0dGdNSkFpazI5dmR6TGYyMC9mSXUyaWRreEpJbTJjLytMY2ltQWoyMUI3VUNSQUtjczcvM0U5VjM1b0txZVBIbk13aHBacEk5Yk9IQ2c4RHNpNXBUaG5PYnlyT3hncFN1M1pqSzkxRFRZREo1TmlaYUVWT1ZUMStNVHphaG9WYzZqMmFST1NDek8vT0ZRMmpXdmhFNlU5ellsdkU2MzdlY2hYVXM3ajRYZHN1UVVqeC81dXd1cHNacjZ0S25PZUhpTEdNMEQza2pIL2xlaXlRa2xRM1FDVExjZjI0RFZOcnFWT0tScERLMEVoNGRqZVBhV3pFajFFa05Wa2FRazQ3OGRzQmx3T0l2Smg3dHB5SXJuVzhxTDlLT2ZScThoTlpyUTVvSkdtOTN5OTZWYTIvakMwV0VjSDg1eEltWXBxMmYxMWE3WU5iZWI4NjFoR1VFRm9lSDZiZHVVVUV1YmJJSVBhQ3NJa2hwc0ZNY0dua1cxYkk2Nm51ZkgrYlpnVzFEOCtwQXR2dWRvZGM9";
///artist url
const QString QQ_ARTIST_URL             = "WERjRFh4WVhsWTdFOStMNWZTSnJGQjlTZHk5RVBqaTUyclRFRjZWVng5bExXNC9GTGdrRFFGQmxTbHpuMmZlSmZacTNLd0VBY21kVDdva1Q0aXlmcU9OWVMwNWtmbFZEbDVRa0JvZCtTWFBLVUtxUjNadmJweVQ2TVF3L0I5WlQ2Z05WcmNPMGZoWjh6d0ZUWHBmTjNKSnhGanVIcEt1L25IS0ZncDU5SzBLZ0o1ZzEvTUludEp4Y2NDbzJWc3VPS21kenpadTVhWDRldkwwUkgxMldSYkpBdC9PUWUvcUVJemZvMzFSVDRKNVBUSzhReUZMYXZWK1BxOG9PYTdWa1JSamxlTnQzNzVtcVJsRUdkRE1ONVhMdGRJQT0=";
const QString QQ_ARTIST_INFO_URL        = "UjR2VWxJSlVDeWVJb3FzY0N5VTBBTUZXeGQ1N3l6ZXB3eU92anVaQW1mRmtTUXE5MkFiZzhjQWZJM2JScmxwSm5FRlA1dUpVUDVEaG9LU3poYmppelgxbFU1OXE1N0N0M2JNWlZKeDdUZCswSXFoYkhYSGNVZURuUldOMExzRmZDUlBROHl0OTFBUnBQc0UxK3RkNnR3PT0=";
const QString QQ_ARTIST_ALBUM_URL       = "REp6M2RPcGhXRE4xb3JCVlQ2VWZRdG9tUnZpbnQxR3N6cDhDaG5LTkZnZHJ2TG5BTEcrVW9JV3B4RmVlUjJMVGlsSUd5cmZHRVRxYTgxK1A5ckV5MElDWXJ1RmFKbVR5YkkyeTltWk5PUTJ1b0tMUW92cVdEcGJBZ2NGajdqZlN3djBsa3NIUFRaOFpCckIxeC9XaGZzSXE3cXlKSG1BUGRwNVAyK1VVMUVnYTZjTGE2MlRRMDVEcVJzZjhxL0lkaEJsQjFtQi9mYjYvT0hHSkRCYnBhMitnaFBqZHJRdm1KOGNBZHo4T3B6eWU4NTRPamM5YVRiRlBWRzg9";
const QString QQ_ARTIST_MOVIE_URL       = "NURjT21UVW9mVmRObnllV2RZNGZVUjB1RDhpOEt5cVE5U2x0L2JrcFl3ODF1TlY2NVVYTEliVzNTZ0U1TitYcW9jcjNJUDU0M1BYMzlUMWtxOTlUWU9NR295U255blB3U3BpTGJlY3NvVDEybmx1TWJrN09tZzlnK1F0WUZQTFREcVM1WDRNQ3pMWW5KK0p2U3dWOXlFNFpxWHNZbFZ1L2FIeHExVWpCTXUrYldwaXBna1c1RGlmU24xb2pFQUxNY0xoeVlETzZXZTV0cTZTV01UazhVc1NVMmcvTUlONEtYZ3pzYVFCZUdBS0kwc3dvL1NnSmRTM2JoVVlsS0xJa2s0endNdz09";
const QString QQ_ARTIST_SIMILAR_URL     = "Q3l2R1ZmOGdsWHRIWTVtZGZxRXZUZ3F0VllzZDlTc0M2TmNkQ0N3aHVNZHVQbG1kb0gwS0JGbGRQN3lWblcrUnYydFFpWUFZTHlaVHcxMmdzbWdvNmRMQVVRV0RYSVZBT3dFWS9qMm5zS2NFdEFZMXJuOXVzQU5SQ1ErWU1BWlFMVGIrOFdTcXcySXlMUmh4UEttTDlpY0tQdFBOc2NLbUlmTjNDQ1ZIOG9yS0dYdGhsMWFWSkhqQkRUcVZlTE5VS3prVEhEYUtoOFdqYUM1dmxRU1RoVExwL3pHRDdyb09SdG5rdkw3YjdTVlpFMEQzRG1BN1BiYmNaVTliWVM5bjg2Mm8xVG1UcU9TUjlGSGQ4MWkvWEE9PQ==";
const QString QQ_ARTIST_LIST_URL        = "UGx5NDFTQzJ2V2Fpb3JxTnVHVVBmM0p1SlJ0RTg0ZGp4LzBxbzBpVjB3bWM2ckZSMytkVGdQSVZZNGRaU0M3YXFkWWxkYUxPS015VWdpQ2RVOVZRMTFPVERJZ0NXOEtHV0p1V2I0TTh5YlBab1FYcGV6eXBFa0hoQmxZZzQ3N1BBUkoveWJraWdYWDVLOVdnOWp0OVMzYityVnNwaFh0d2VlcVI1dUkwUFI4UTFGdjBpZjhoZFBWVnUzWUlyWk1Qc0praUVtSUVXelpodGkrRlVsVENSWFl6R0V2eXZqeDRrTWNSQWFwTFZucnlYeEJsNkpDeTg3d0tKUzFVcW9RY2ZtT2NuWUNMby9HSEc3b1hubDRIdk05WTlGYz0=";
///album url
const QString QQ_ALBUM_URL              = "THpHd1YyR3FTL3RCQ2pLMFVwSTlrTEc1WUszYXBKNWFqTHRSMXMrSzJIdUJURWx3REoyOWZ0dmRxRXpmSGdaTlRGMTltYmdmZlU4RkFMbWRuTVhtZ0VBWmRVM3A1eVgxVVgzcUZwYkloQzdSNWJSL3VjTGZTNTRBbWJWekRxZ1NXYkdBR1NocW40cm9wRVYrU1EweVN1MHZFeVliM09zUmQ5eHI1RzBUZjU4by9MZVAyZnh1dXR1QkJhdE8zQnk5SlFCcm1MZHVabTRSTkFJSGhmNEgyQVlCc1o3UjR0VGQ=";
///movie url
const QString QQ_MOVIE_INFO_URL         = "ZjhkZmd4LzNnQi9seFJpUmZ0L0hLQkZ1dFdnME5lOWI5dlgvUFpHUUw5U2xQdzJXZzhxditTWTNTWllKTVp4dFo2bmlqc1Y4TUpoeTFEdUFnbkNVOE5WL0RVYVFzSHR0UFpzN2pBPT0=";
const QString QQ_MOVIE_KEY_URL          = "cEo4MkdYaVNIUEJFTGNnd0hGai8zUFVWQStTQ3NyamM1YmovTzdGQWRwRFU2OExQV0MxMUxSN0NkSmJrT3MzTTNVaFhSUytNWmFrKys3ODdhWldaNWljZXBaRmFHeUg1dHdGb1JSNEJpQ3orZFIwVUIrUURJUFRJZ25SakVpN20=";
///toplist url
const QString QQ_TOPLIST_URL            = "NGtsYzRNNjFCSlhOVUFnMk0rSHFpZll4WUdsY0ZWcERWWXFtbnBIU2JGV0lWLzhNU2NFWUpaS3ZaOTZFdm9VQlBLdzl0S0FOTEhaNDhpQmkzSGt2QXFLcnhDNjNuZHNQOVM2Tk1UMjRReHVFRnQ3eS9JakUwOHBYa2RXUzNtcGQwaTNEdUJEZXlYdllya2xPWXVzRkFqRFFWV29nSkowN2NuNmxxRkhTaFFRZzhCZSs2bXIzK1hzNHhoakppdGM5TTVFNlkwV2pRV3hpbzR4WTFNdU55STZ2UVdnVVRVRlBZMjA2U1pzbVdobWd6S3lEMGZtVWJpbUhwT011U1pJRw==";
///comment url
const QString QQ_COMMENT_URL            = "Zk9wcGVJRXMxaTg5enBsVEFGc0hGWVpkT0gvVHNCNDBHSXU0anR6bzdTQnpEN2dlZDg4TllZa256aUhZUys1UURDdFV3ZFZmZmRzSFlXVDhlcTM4TFQvNnpWU0VqR1k5WGZZaWpnPT0=";
const QString QQ_COMMENT_SONG_URL       = "d0F1WXh6MWt2SXN6WktuU24wUTNXNERCZmJXb296QUhicFFZb29DSjhEeFN2dldqWHgrL0cvSG1sRVdaWHMzbGliaWFzbklEaTQ5UzZxY3RVNlpqU1huSDJCWVRCYU5YQ25HT2ozVE95aGRXUy9malNrNU9GcUVHSTkvMHA5blNxUE10ZW1lNEpLMWM2dFA1cHQzdjdDVDRXb2IxbGVhbXRXQzJRR1FrNWtrb3FmV01KVG5TVkxyUEVCYmxjMC9zOVZSWHVTRThmSzkzalZBd0p2bnRkZXh0QmRTV3N3OVh6alZ3UWJ4ck8xdEZ3U2xCdmNPT0RkRHpRb3phR3Z6TXZDcjd5TzU2cHJoMElLeFE=";
const QString QQ_COMMENT_PLAYLIST_URL   = "c1BKYmVFa1FRc0trZ0NtVVVMOEMrNXNDWFRiYzJLYXBQaUdXZWZobjlrZy94cVdNNTlJSTQ1S0xjWlpBSEhPWVlzZXREb0ZLSkFoVWJteFpqRlNiRjNRSHRDNVFEbXRyRnFRVW9JTTc1MW11ZFp4cVh2QmxFQXplWHZEeWNRUERBYThYM0dqZFZqeVVTYW1GL2pkeHpkV2EvbnlNakdIc0UrY2MrNVRKWWxKQ3RmTEdSYmt6LzRTU2JFQm9iOG96VXZ6TVlveE5rSXpvQUlaL2JXN2RKWnJXT1BjcjF1MEsrelI0VS9kOVc0SndkQk5LNWhRekp2WTFnd1VBdzJpMytDeENJenN0S0VKUS9yTVk=";
///playlist url
const QString QQ_PLAYLIST_URL           = "M2xMcmljcUNoVDNKemw1YWhEWkIxUStMUUNySnYwdUxHUlQvRTcyanBPRnR6TEU2ZlBUZXc3QllEd25lSjBKT2hMeGYrQnNZMmhiSmZKd3UrWjJISWNJWlJ2MFpFTm95VjB2REdLM2RPUVlpeWhGblUvZ0toOWJFTUlKak81ZElybERrTk5JSHJBUXMyZjJraTcyejZVUE1FbDJtMUhwU3VyWFl4Tk52QVM4QnliWFlERzEzdGw1aFBSb0lRVy9NVThlT2VOOFY3MlV5RDFtcVBRelFhbjNzRUdqQWtPbVJKMllWWGdOZFROKzZPcnc1bCtySnd1R0hINVdzemJWR3R2NEd6OFhOQlhVME14eEI3WVlXTFpzZGVuUDZLR2Nw";
const QString QQ_PLAYLIST_INFO_URL      = "OVNWZXI3NkNOVXVONnZMWXNMaitKR3NzcmJKcFNKTEpaNTBQT3RyTzM3OWJ2Y2c4dTFlOHpHcDh0c1p3OFpFWEJySUtUQjRUUDFVU0YyRGdjR3RGZmt2YlVTSFMyaEE1TWtKRDVjcy9qZXNWL3hKbFR4SDljK05PVjY0WXZRdUVHNFZhRkNpZ2EvNGRaWmpJWFhRM0JPS3pVa0w4Tjh4NUpFd0M5Z0dtVGNMNEMrZzUzTkxZeDRDNDlYM01BVkpSWFdjUUkzS25UMVczZUF1MnZjak80Qk15QkRDYzkrM2lUTEoyeG1HSmlMUFNxckF0dmh1bTNUcDhhZ1Z4WTdKTXRVOFhINDBZYm9XUDUzVzdjQXpuTldoeTJmVFZDTGh0UHo0Q3lJSHZOb1A4VnkyQUxGQnNpdFZsd1gzQ0lSQ0Q=";
///recommend url
const QString QQ_RECOMMEND_URL          = "dEFUcDF6NjZKOVZ1bk01OTFhVHZBd3Jlb1J2K08xVkZsVkw4R054SGp3eXluSS9pREZrMGUwUEo1WnJCbHVla0tjdHAvajViN3puMzUzNVJFdXBoTzArbHl4amZObXhCcnczUTh6TXZxMFBvTWFUQXlQTy9hMHVacWJvUUE5NGpvbmVXd3VKMGJCcHVkRzk5bmZ1N0tPL2RCUjNRZGFMNlU4MGlOYmJaSEpaRWxDVmkzNFVoSklPVHg1dXByVDZNanArZkpzMVovY2JBM0IxN0RoMWlwUWVQakxiZlQvMEt4b2JNWGZyQldoQUs5MUsxUTY3eDk4UCtFRm9PaTA1TkpkSXVzUWx6dUJsaTBCV3FMc2g2djNNRkZDVEltZmNVTzN5ZTg4cUZJZmpnUm13RklGTnJHNEhTSHAvdmVmWUdaYVJBK0JwVlM5Rlk5Sm13aXd0NjlrZHFqU0V2NTlEa3VWWnVudUZYWFJ5cWMveVdDQ1BJeDY3bEJpczZvekJ6OVFEMXJtQmRxUFk9";
///suggest url
const QString QQ_SUGGEST_URL            = "YVZrME9hWGRKNjJySkE1djh3T0wwVG1TY1FzVU94ODY2aW83TEFqRVROWVRpU2EzcG00NGxvZ0RYcm8xdE50bTkvSHdKMjc3aW9kbENxbnpRMnU4RzVtRVJDZW4xMENuRytnVDhWMEV3WUtrME12VFlxNTRKdGtaMGhSVDJHRmdONVY5aU9uOXBkSDdqK1drSEZnYW9tZi96NHVOc0NLQWVXRi9iV0t0cnNGckVDbjF6WVRaWmNJN1B4R0hpOVM5MUZxODFjTk16N3pEem95UVphNW81a3hSY1RjNXZzNzVzVzBvZjRkZGlHUjcvQTBOZEdKSDFnPT0=";


class QNetworkAccessManager;

/*! @brief The class to qq query interface.
 * @author Greedysky <greedysky@163.com>
 */
class MUSIC_NETWORK_EXPORT MusicQQQueryInterface
{
public:
    /*!
     * Read tags(size\bitrate\url) from query results.
     */
    void readFromMusicSongAttribute(MusicObject::MusicSongInformation *info, const QVariantMap &key, int bitrate);
    /*!
     * Read tags(size\bitrate\url) from query results.
     */
    void readFromMusicSongAttribute(MusicObject::MusicSongInformation *info, const QVariantMap &key, const QString &quality, bool all);
    /*!
     * Read tags(size\bitrate\url) from query results.
     */
    void readFromMusicSongAttributePlus(MusicObject::MusicSongInformation *info, const QVariantMap &key, int bitrate);
    /*!
     * Read tags(size\bitrate\url) from query results.
     */
    void readFromMusicSongAttributePlus(MusicObject::MusicSongInformation *info, const QVariantMap &key);

    /*!
     * Get music key.
     */
    QString getMusicPath(const QString &file, const QString &mid);

};

#endif // MUSICQQQUERYINTERFACE_H
