#ifndef MUSICLIBEXPORTGLOBAL_H
#define MUSICLIBEXPORTGLOBAL_H

#include <QtCore/qglobal.h>

#ifdef QT_DEBUG
    #define MUSIC_DEBUG
#endif

#ifdef MUSIC_LIBRARY
#  define MUSIC_WIDGET_EXPORT Q_DECL_EXPORT
#  define MUSIC_CORE_EXPORT Q_DECL_EXPORT
#  define MUSIC_GUI_EXPORT Q_DECL_EXPORT
#else
#  define MUSIC_WIDGET_EXPORT Q_DECL_IMPORT
#  define MUSIC_CORE_EXPORT Q_DECL_IMPORT
#  define MUSIC_GUI_EXPORT Q_DECL_IMPORT
#endif

#endif // MUSICLIBEXPORTGLOBAL_H
