# =================================================
# * This file is part of the TTK Music Player project
# * Copyright (C) 2015 - 2020 Greedysky Studio
#
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 3 of the License, or
# * (at your option) any later version.
#
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
#
# * You should have received a copy of the GNU General Public License along
# * with this program; If not, see <http://www.gnu.org/licenses/>.
# =================================================

INCLUDEPATH += $$PWD \
               $$PWD/common \
               $$PWD/music/wy \
               $$PWD/music/xm \
               $$PWD/music/kg \
               $$PWD/music/kw \
               $$PWD/music/bd \
               $$PWD/music/qq \
               $$PWD/music/yyt \
               $$PWD/radio/fm \
               $$PWD/radio/dj \
               $$PWD/radio/mv

HEADERS  += \
    $$PWD/common/musicdatadownloadthread.h \
    $$PWD/common/musictextdownloadthread.h \
    $$PWD/common/musicdatatagdownloadthread.h \
    $$PWD/common/musicdownloadsourcethread.h \
    $$PWD/common/musicnetworkthread.h \
    $$PWD/common/musicnetworkproxy.h \
    $$PWD/common/musicnetworkoperator.h \
    $$PWD/common/musicdownloadbackgroundthread.h \
    $$PWD/common/musicdownloadqueuecache.h \
    $$PWD/common/musicidentifysongsthread.h \
    $$PWD/common/musicsourceupdatethread.h \
    $$PWD/common/musicdownloadcounterpvthread.h \
    $$PWD/common/musicdownloadbackgroundremotethread.h \
    $$PWD/music/wy/musicdownloadwyinterface.h \
    $$PWD/music/wy/musicdownloadquerywythread.h \
    $$PWD/music/wy/musicwytextdownloadthread.h \
    $$PWD/music/wy/musicwydiscoverlistthread.h \
    $$PWD/music/wy/musicdownloadquerywyalbumthread.h \
    $$PWD/music/wy/musicdownloadquerywyartistthread.h \
    $$PWD/music/wy/musicdownloadquerywyplaylistthread.h \
    $$PWD/music/wy/musicdownloadquerywytoplistthread.h \
    $$PWD/music/wy/musicdownloadquerywymoviethread.h \
    $$PWD/music/wy/musicdownloadquerywyrecommendthread.h \
    $$PWD/music/wy/musicdownloadquerywyartistlistthread.h \
    $$PWD/music/wy/musicwycommentsthread.h \
    $$PWD/music/wy/musicwyartistsimilarthread.h \
    $$PWD/music/wy/musicwysongsuggestthread.h \
    $$PWD/music/wy/musicwytranslationthread.h \
    $$PWD/music/xm/musicdownloadxminterface.h \
    $$PWD/music/xm/musicdownloadqueryxmthread.h \
    $$PWD/music/xm/musicdownloadqueryxmalbumthread.h \
    $$PWD/music/xm/musicdownloadqueryxmartistthread.h \
    $$PWD/music/xm/musicxmtextdownloadthread.h \
    $$PWD/music/xm/musicdownloadqueryxmplaylistthread.h \
    $$PWD/music/xm/musicdownloadqueryxmtoplistthread.h \
    $$PWD/music/xm/musicdownloadqueryxmmoviethread.h \
    $$PWD/music/xm/musicdownloadqueryxmrecommendthread.h \
    $$PWD/music/xm/musicdownloadqueryxmartistlistthread.h \
    $$PWD/music/xm/musicxmdiscoverlistthread.h \
    $$PWD/music/xm/musicxmcommentsthread.h \
    $$PWD/music/xm/musicxmsongsuggestthread.h \
    $$PWD/music/xm/musicxmartistsimilarthread.h \
    $$PWD/music/kg/musicdownloadquerykgthread.h \
    $$PWD/music/kg/musicdownloadquerykgalbumthread.h \
    $$PWD/music/kg/musicdownloadquerykgartistthread.h \
    $$PWD/music/kg/musicdownloadkginterface.h \
    $$PWD/music/kg/musicdownloadquerykgplaylistthread.h \
    $$PWD/music/kg/musicdownloadquerykgtoplistthread.h \
    $$PWD/music/kg/musicdownloadquerykgmoviethread.h \
    $$PWD/music/kg/musicdownloadquerykgrecommendthread.h \
    $$PWD/music/kg/musicdownloadquerykgartistlistthread.h \
    $$PWD/music/kg/musickgdiscoverlistthread.h \
    $$PWD/music/kg/musickgcommentsthread.h \
    $$PWD/music/kg/musickgsongsuggestthread.h \
    $$PWD/music/kg/musickgartistsimilarthread.h \
    $$PWD/music/kw/musicdownloadquerykwthread.h \
    $$PWD/music/kw/musicdownloadquerykwalbumthread.h \
    $$PWD/music/kw/musicdownloadquerykwartistthread.h \
    $$PWD/music/kw/musicdownloadkwinterface.h \
    $$PWD/music/kw/musickwtextdownloadthread.h \
    $$PWD/music/kw/musicdownloadquerykwplaylistthread.h \
    $$PWD/music/kw/musicdownloadquerykwtoplistthread.h \
    $$PWD/music/kw/musicdownloadquerykwmoviethread.h \
    $$PWD/music/kw/musicdownloadquerykwrecommendthread.h \
    $$PWD/music/kw/musicdownloadquerykwartistlistthread.h \
    $$PWD/music/kw/musickwdiscoverlistthread.h \
    $$PWD/music/kw/musickwcommentsthread.h \
    $$PWD/music/kw/musickwbackgroundthread.h \
    $$PWD/music/kw/musickwsongsuggestthread.h \
    $$PWD/music/kw/musickwartistsimilarthread.h \
    $$PWD/music/bd/musicdownloadquerybdthread.h \
    $$PWD/music/bd/musicdownloadquerybdalbumthread.h \
    $$PWD/music/bd/musicdownloadquerybdartistthread.h \
    $$PWD/music/bd/musicdownloadbdinterface.h \
    $$PWD/music/bd/musicdownloadquerybdplaylistthread.h \
    $$PWD/music/bd/musicdownloadquerybdlearnthread.h \
    $$PWD/music/bd/musicdownloadquerybdtoplistthread.h \
    $$PWD/music/bd/musicdownloadquerybdmoviethread.h \
    $$PWD/music/bd/musicdownloadquerybdrecommendthread.h \
    $$PWD/music/bd/musicdownloadquerybdartistlistthread.h \
    $$PWD/music/bd/musicbddiscoverlistthread.h \
    $$PWD/music/bd/musicbdcommentsthread.h \
    $$PWD/music/bd/musicbdsongsuggestthread.h \
    $$PWD/music/bd/musicbdartistsimilarthread.h \
    $$PWD/music/bd/musicbdtranslationthread.h \
    $$PWD/music/qq/musicdownloadqueryqqthread.h \
    $$PWD/music/qq/musicdownloadqueryqqalbumthread.h \
    $$PWD/music/qq/musicdownloadqueryqqartistthread.h \
    $$PWD/music/qq/musicdownloadqqinterface.h \
    $$PWD/music/qq/musicqqtextdownloadthread.h \
    $$PWD/music/qq/musicdownloadqueryqqplaylistthread.h \
    $$PWD/music/qq/musicdownloadqueryqqtoplistthread.h \
    $$PWD/music/qq/musicdownloadqueryqqmoviethread.h \
    $$PWD/music/qq/musicdownloadqueryqqrecommendthread.h \
    $$PWD/music/qq/musicdownloadqueryqqartistlistthread.h \
    $$PWD/music/qq/musicqqdiscoverlistthread.h \
    $$PWD/music/qq/musicqqcommentsthread.h \
    $$PWD/music/qq/musicqqbackgroundthread.h \
    $$PWD/music/qq/musicqqsongsuggestthread.h \
    $$PWD/music/qq/musicqqartistsimilarthread.h \
    $$PWD/music/yyt/musicdownloadqueryyytthread.h \
    $$PWD/radio/fm/musicfmradiochannelthread.h \
    $$PWD/radio/fm/musicfmradiotextdownloadthread.h \
    $$PWD/radio/fm/musicfmradiosongsthread.h \
    $$PWD/radio/fm/musicfmradiothreadabstract.h \
    $$PWD/radio/dj/musicdjradiocategorythread.h \
    $$PWD/radio/dj/musicdjradioprogramthread.h \
    $$PWD/radio/dj/musicdjradioprogramcategorythread.h \
    $$PWD/radio/dj/musicdjradiothreadabstract.h \
    $$PWD/radio/mv/musicmvradiocategorythread.h \
    $$PWD/radio/mv/musicmvradioprogramthread.h \
    $$PWD/radio/mv/musicmvradiothreadabstract.h \
    $$PWD/musicnetworkdefines.h \
    $$PWD/musicnetworkabstract.h \
    $$PWD/musicdownloadthreadabstract.h \
    $$PWD/musicdownloadqueryfactory.h \
    $$PWD/musicdownloadquerythreadabstract.h \
    $$PWD/musicdownloadcommentsthread.h \
    $$PWD/musicdownloaddiscoverlistthread.h \
    $$PWD/musicdownloadpagingthread.h \
    $$PWD/musicdownloadqueryalbumthread.h \
    $$PWD/musicdownloadqueryartistthread.h \
    $$PWD/musicdownloadqueryplaylistthread.h \
    $$PWD/musicdownloadquerytoplistthread.h \
    $$PWD/musicdownloadqueryrecommendthread.h \
    $$PWD/musicdownloadquerymoviethread.h \
    $$PWD/musicdownloadsongsuggestthread.h \
    $$PWD/musicdownloadsimilarthread.h \
    $$PWD/musicdownloadqueryartistlistthread.h \
    $$PWD/musicdownloadtranslationthread.h \
    $$PWD/musicdownloadmanager.h


SOURCES += \
    $$PWD/common/musicdatadownloadthread.cpp \
    $$PWD/common/musictextdownloadthread.cpp \
    $$PWD/common/musicdatatagdownloadthread.cpp \
    $$PWD/common/musicdownloadsourcethread.cpp \
    $$PWD/common/musicnetworkthread.cpp \
    $$PWD/common/musicnetworkproxy.cpp \
    $$PWD/common/musicnetworkoperator.cpp \
    $$PWD/common/musicdownloadbackgroundthread.cpp \
    $$PWD/common/musicdownloadqueuecache.cpp \
    $$PWD/common/musicidentifysongsthread.cpp \
    $$PWD/common/musicsourceupdatethread.cpp \
    $$PWD/common/musicdownloadcounterpvthread.cpp \
    $$PWD/common/musicdownloadbackgroundremotethread.cpp \
    $$PWD/music/wy/musicdownloadwyinterface.cpp \
    $$PWD/music/wy/musicdownloadquerywythread.cpp \
    $$PWD/music/wy/musicwytextdownloadthread.cpp \
    $$PWD/music/wy/musicwydiscoverlistthread.cpp \
    $$PWD/music/wy/musicdownloadquerywyalbumthread.cpp \
    $$PWD/music/wy/musicdownloadquerywyartistthread.cpp \
    $$PWD/music/wy/musicdownloadquerywyplaylistthread.cpp \
    $$PWD/music/wy/musicdownloadquerywytoplistthread.cpp \
    $$PWD/music/wy/musicdownloadquerywymoviethread.cpp \
    $$PWD/music/wy/musicdownloadquerywyrecommendthread.cpp \
    $$PWD/music/wy/musicdownloadquerywyartistlistthread.cpp \
    $$PWD/music/wy/musicwycommentsthread.cpp \
    $$PWD/music/wy/musicwysongsuggestthread.cpp \
    $$PWD/music/wy/musicwyartistsimilarthread.cpp \
    $$PWD/music/wy/musicwytranslationthread.cpp \
    $$PWD/music/xm/musicdownloadxminterface.cpp \
    $$PWD/music/xm/musicdownloadqueryxmthread.cpp \
    $$PWD/music/xm/musicdownloadqueryxmalbumthread.cpp \
    $$PWD/music/xm/musicdownloadqueryxmartistthread.cpp \
    $$PWD/music/xm/musicxmtextdownloadthread.cpp \
    $$PWD/music/xm/musicdownloadqueryxmplaylistthread.cpp \
    $$PWD/music/xm/musicdownloadqueryxmtoplistthread.cpp \
    $$PWD/music/xm/musicdownloadqueryxmmoviethread.cpp \
    $$PWD/music/xm/musicdownloadqueryxmrecommendthread.cpp \
    $$PWD/music/xm/musicdownloadqueryxmartistlistthread.cpp \
    $$PWD/music/xm/musicxmdiscoverlistthread.cpp \
    $$PWD/music/xm/musicxmcommentsthread.cpp \
    $$PWD/music/xm/musicxmsongsuggestthread.cpp \
    $$PWD/music/xm/musicxmartistsimilarthread.cpp \
    $$PWD/music/kg/musicdownloadquerykgthread.cpp \
    $$PWD/music/kg/musicdownloadquerykgalbumthread.cpp \
    $$PWD/music/kg/musicdownloadquerykgartistthread.cpp \
    $$PWD/music/kg/musicdownloadkginterface.cpp \
    $$PWD/music/kg/musicdownloadquerykgplaylistthread.cpp \
    $$PWD/music/kg/musicdownloadquerykgtoplistthread.cpp \
    $$PWD/music/kg/musicdownloadquerykgmoviethread.cpp \
    $$PWD/music/kg/musicdownloadquerykgrecommendthread.cpp \
    $$PWD/music/kg/musicdownloadquerykgartistlistthread.cpp \
    $$PWD/music/kg/musickgdiscoverlistthread.cpp \
    $$PWD/music/kg/musickgcommentsthread.cpp \
    $$PWD/music/kg/musickgsongsuggestthread.cpp \
    $$PWD/music/kg/musickgartistsimilarthread.cpp \
    $$PWD/music/kw/musicdownloadquerykwthread.cpp \
    $$PWD/music/kw/musicdownloadquerykwalbumthread.cpp \
    $$PWD/music/kw/musicdownloadquerykwartistthread.cpp \
    $$PWD/music/kw/musicdownloadkwinterface.cpp \
    $$PWD/music/kw/musickwtextdownloadthread.cpp \
    $$PWD/music/kw/musicdownloadquerykwplaylistthread.cpp \
    $$PWD/music/kw/musicdownloadquerykwtoplistthread.cpp \
    $$PWD/music/kw/musicdownloadquerykwmoviethread.cpp \
    $$PWD/music/kw/musicdownloadquerykwrecommendthread.cpp \
    $$PWD/music/kw/musicdownloadquerykwartistlistthread.cpp \
    $$PWD/music/kw/musickwdiscoverlistthread.cpp \
    $$PWD/music/kw/musickwcommentsthread.cpp \
    $$PWD/music/kw/musickwbackgroundthread.cpp \
    $$PWD/music/kw/musickwsongsuggestthread.cpp \
    $$PWD/music/kw/musickwartistsimilarthread.cpp \
    $$PWD/music/bd/musicdownloadquerybdthread.cpp \
    $$PWD/music/bd/musicdownloadquerybdalbumthread.cpp \
    $$PWD/music/bd/musicdownloadquerybdartistthread.cpp \
    $$PWD/music/bd/musicdownloadbdinterface.cpp \
    $$PWD/music/bd/musicdownloadquerybdplaylistthread.cpp \
    $$PWD/music/bd/musicdownloadquerybdlearnthread.cpp \
    $$PWD/music/bd/musicdownloadquerybdtoplistthread.cpp \
    $$PWD/music/bd/musicdownloadquerybdmoviethread.cpp \
    $$PWD/music/bd/musicdownloadquerybdrecommendthread.cpp \
    $$PWD/music/bd/musicdownloadquerybdartistlistthread.cpp \
    $$PWD/music/bd/musicbddiscoverlistthread.cpp \
    $$PWD/music/bd/musicbdcommentsthread.cpp \
    $$PWD/music/bd/musicbdsongsuggestthread.cpp \
    $$PWD/music/bd/musicbdartistsimilarthread.cpp \
    $$PWD/music/bd/musicbdtranslationthread.cpp \
    $$PWD/music/qq/musicdownloadqueryqqthread.cpp \
    $$PWD/music/qq/musicdownloadqueryqqalbumthread.cpp \
    $$PWD/music/qq/musicdownloadqueryqqartistthread.cpp \
    $$PWD/music/qq/musicdownloadqqinterface.cpp \
    $$PWD/music/qq/musicqqtextdownloadthread.cpp \
    $$PWD/music/qq/musicdownloadqueryqqplaylistthread.cpp \
    $$PWD/music/qq/musicdownloadqueryqqtoplistthread.cpp \
    $$PWD/music/qq/musicdownloadqueryqqmoviethread.cpp \
    $$PWD/music/qq/musicdownloadqueryqqrecommendthread.cpp \
    $$PWD/music/qq/musicdownloadqueryqqartistlistthread.cpp \
    $$PWD/music/qq/musicqqdiscoverlistthread.cpp \
    $$PWD/music/qq/musicqqcommentsthread.cpp \
    $$PWD/music/qq/musicqqbackgroundthread.cpp \
    $$PWD/music/qq/musicqqsongsuggestthread.cpp \
    $$PWD/music/qq/musicqqartistsimilarthread.cpp \
    $$PWD/music/yyt/musicdownloadqueryyytthread.cpp \
    $$PWD/radio/fm/musicfmradiochannelthread.cpp \
    $$PWD/radio/fm/musicfmradiotextdownloadthread.cpp \
    $$PWD/radio/fm/musicfmradiosongsthread.cpp \
    $$PWD/radio/fm/musicfmradiothreadabstract.cpp \
    $$PWD/radio/dj/musicdjradiocategorythread.cpp \
    $$PWD/radio/dj/musicdjradioprogramthread.cpp \
    $$PWD/radio/dj/musicdjradioprogramcategorythread.cpp \
    $$PWD/radio/dj/musicdjradiothreadabstract.cpp \
    $$PWD/radio/mv/musicmvradiocategorythread.cpp \
    $$PWD/radio/mv/musicmvradioprogramthread.cpp \
    $$PWD/radio/mv/musicmvradiothreadabstract.cpp \
    $$PWD/musicnetworkabstract.cpp \
    $$PWD/musicdownloadthreadabstract.cpp \
    $$PWD/musicdownloadqueryfactory.cpp \
    $$PWD/musicdownloadquerythreadabstract.cpp \
    $$PWD/musicdownloadcommentsthread.cpp \
    $$PWD/musicdownloaddiscoverlistthread.cpp \
    $$PWD/musicdownloadpagingthread.cpp \
    $$PWD/musicdownloadqueryalbumthread.cpp \
    $$PWD/musicdownloadqueryartistthread.cpp \
    $$PWD/musicdownloadqueryplaylistthread.cpp \
    $$PWD/musicdownloadquerytoplistthread.cpp \
    $$PWD/musicdownloadqueryrecommendthread.cpp \
    $$PWD/musicdownloadquerymoviethread.cpp \
    $$PWD/musicdownloadsongsuggestthread.cpp \
    $$PWD/musicdownloadsimilarthread.cpp \
    $$PWD/musicdownloadqueryartistlistthread.cpp \
    $$PWD/musicdownloadtranslationthread.cpp \
    $$PWD/musicdownloadmanager.cpp
