# Author: Greedysky <greedysky@163.com>

name: win7

on: workflow_call

env:
  TTK_MODULE: TTKMusicPlayer
  TTK_VERSTION: 4.2.0.0

jobs:
  build:
    name: Build on win64 Qt5
    strategy:
      matrix:
        qt_version: [5.15.2]
        os: [windows-2022]

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4

      - name: Cache Qt
        uses: actions/cache@v4
        with:
          path: ${{runner.workspace}}/Qt
          key: ${{runner.os}}-QtCache-${{matrix.qt_version}}

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{matrix.qt_version}}
          host: windows
          arch: win64_mingw81
          target: desktop
          cache: 'true'

      - name: Create build dir
        shell: bash
        run: mkdir build
        working-directory: ${{runner.workspace}}

      - name: Build project
        shell: cmd
        run: |
          qmake -v
          cmake --version
          cmake %GITHUB_WORKSPACE% -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}/install -DTTK_QT_VERSION=5
          make && make install
        working-directory: ${{runner.workspace}}/build

      - name: Build package
        run: |
          bitsadmin /transfer job https://github.com/Greedysky/Resource/releases/download/1.0.0.0/theme.7z ${{runner.workspace}}/install/theme.7z
          7z x theme.7z
          mv GTheme ${{env.TTK_MODULE}}/${{env.TTK_VERSTION}}
          windeployqt ${{env.TTK_MODULE}}/${{env.TTK_VERSTION}}/TTKService.exe
          cp ${{env.TTK_MODULE}}/${{env.TTK_VERSTION}}/libgcc_s_seh-1.dll ${{env.TTK_MODULE}}
          cp ${{env.TTK_MODULE}}/${{env.TTK_VERSTION}}/libstdc++-6.dll ${{env.TTK_MODULE}}
          cp ${{env.TTK_MODULE}}/${{env.TTK_VERSTION}}/libwinpthread-1.dll ${{env.TTK_MODULE}}
          cp ${{runner.workspace}}/Qt/${{matrix.qt_version}}/mingw81_64/bin/Qt5Xml.dll ${{env.TTK_MODULE}}/${{env.TTK_VERSTION}}
          7z a ${{env.TTK_MODULE}}-${{env.TTK_VERSTION}}-win7-x64.7z ${{env.TTK_MODULE}}
        working-directory: ${{runner.workspace}}/install

      - name: Archive artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{env.TTK_VERSTION}}
          token: ${{secrets.GITHUB_TOKEN}}
          generate_release_notes: false
          files: ${{runner.workspace}}/install/${{env.TTK_MODULE}}-${{env.TTK_VERSTION}}-win7-x64.7z
